package com.voting.pages;

import java.io.IOException;
import java.io.PrintWriter;
import java.sql.SQLException;

import javax.servlet.ServletConfig;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.Cookie;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import com.voting.dao.CandidateDao;
import com.voting.dao.CandidateDaoImpl;
import com.voting.dao.UserDao;
import com.voting.dao.UserDaoImpl;
import com.voting.pojos.User;

import static com.voting.utils.DBUtils.*;

/**
 * Servlet implementation class LoginServlet
 */
//@WebServlet(value = "/authenticate", loadOnStartup = 1)
public class LoginServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;
	private UserDao userDao;
	private CandidateDao candidateDao;
	
	public LoginServlet() {
		System.out.println("in def ctor of "+getClass());
	}

	/**
	 * @see Servlet#init()
	 */
	// overriding form of the method can't add any new | broader checked excs
	public void init() throws ServletException {
		System.out.println("in init " + getClass());
		try {
			//get servlet config
			ServletConfig config=getServletConfig();
			String url=config.getInitParameter("db_url");
			String userName=config.getInitParameter("user_name");			
			String pwd=config.getInitParameter("password");
			
			// open connection
			openConnection(url,userName,pwd);
			// create user dao instance
			userDao = new UserDaoImpl();
			//create candidate dao instance
			candidateDao=new CandidateDaoImpl();
			System.out.println(getClass() + " inited !");
		} catch (Exception e) {
			System.out.println(e);
			// centralized exc handling in servlets
			// re throw the same exc to WC , by wrapping it in ServletException
			throw new ServletException("err in init", e);
		}
	}

	/**
	 * @see Servlet#destroy()
	 */
	public void destroy() {
		System.out.println("in destroy " + getClass());
		// dao's clean up
		try {
			userDao.cleanUp();
			candidateDao.cleanUp();
			closeConnection();
		} catch (Exception e) {
			System.out.println(e);
			// how to inform WC about the exc?
			throw new RuntimeException("err in destroy", e);
		}

	}

	/**
	 * @see HttpServlet#doPost(HttpServletRequest request, HttpServletResponse
	 *      response)
	 */
	@Override
	protected void doPost(HttpServletRequest request, HttpServletResponse response)
			throws ServletException, IOException {
		System.out.println("in do-post" + getClass());
		response.setContentType("text/html");
		try (PrintWriter pw = response.getWriter()) {
			// get request data - email n password
			String email = request.getParameter("em");
			String pwd = request.getParameter("pass");
			// invoke dao's method for sign in
			User user = userDao.signIn(email, pwd);
			// null checking
			if (user != null) {
				// authentication successful 
				//1. get HttpSession from WC
				HttpSession session=request.getSession();
				System.out.println(getClass()+" session "
				+session.isNew());//true
				System.out.println("Session ID "+session.getId());
				//2. save authenticated user details - under session scope
				session.setAttribute("user_dtls", user);
				//3. save  dao instaances  under session
				session.setAttribute("user_dao", userDao);
				session.setAttribute("candidate_dao", candidateDao);
				//now proceed to
				// role based authorization

				if (user.getUserRole().equals("admin")) {
					response.sendRedirect("admin");
				} else if (user.getUserRole().equals("voter")) {
					if (user.isStatus())
						response.sendRedirect("logout");
					else
						response.sendRedirect("list");
					//WC sends temp redirect 
					//Resp Packet - SC 302 , 
					//Resp headers - Location - list , Set-Cookie :
					//JSESSIONID : alpha numeric string generated by WC
					// body - empty
				}

			} else {
				// invalid login
				pw.print("<h5>Invalid Login , Pls <a href='login.html'>Retry</a></h5>");
			}

		} catch (Exception e) {
			// re throw exc to the caller - WC
			throw new ServletException("err in do-post", e);
		}
	}

}
